### PR TITLE
feat(validation): add Func validation to have the ability to do customized validations #5698

### PR DESCRIPTION
**Pull request by hamidrabedi**
#5698
I tried to do this with the least amount of code, and small changes on the main code

### CODE REVIEW

**Comment by hamidrabedi** [comment]
I have no idea why tests are failing. and for deepSource, they are not even my code, I'm confused.

**Comment by flycash** [comment]
> I have no idea why tests are failing. and for deepSource, they are not even my code, I'm confused.
you can ignore this.

But what issue does this merge request aim to solve?

**Comment by hamidrabedi** [comment]
this one:
https://github.com/beego/beego/issues/5698

**Comment by flycash** [comment]
I have another idea that we allow users define the specific function on the type:
```go
type User struct {

}

func (u User) Validate() error {
// users write the code here
}
```
And for Beego:
```go
// validate the field based on tag
validator.Validate()
// check if the specific instance has the function Validate()
if val, ok := obj.(interface{Validate() error}; ok{
   err = val.Validate()
} 
```

**Comment by hamidrabedi** [comment]
i don't get it, you want to do only one validation for the whole struct? and not per field? or you want to have like both?

**Comment by flycash** [comment]
never mind, I will find someone to implement this new feature and then you can help to review it and confirm if it solves your problem.

**Comment by flycash** [comment]
https://github.com/beego/beego/pull/5703 we already support custom functions, you can find the example.

**Pull request closed without merging**
