### PR TITLE
fix(orm): txOrm miss debug log

### LINKED ISSUE #4674: beego v2: Tx sql logs are not printed when using orm.NewOrm().DoTx
beego v2.0.2-0.20210623154053-2207201e3877 (actually since beego v2):

`COMMIT` / `ROLLBACK` and the SQLs that executed in Tx closure are not printed. The TX orm debug log only contains a `START TRANSACTION` line:

`[ORM]2021/06/25 15:26:55  -[Queries/default] - [  OK /  db.BeginTx /     0.3ms] - [START TRANSACTION]`

```go

orm.Debug = true

orm.NewOrm().DoTx(func(ctx context.Context, txOrm orm.TxOrmer) (txerr error) {
  _, txerr = txOrm.QueryTable(&xxx{}).Count()
  return
})

```

### PR DESCRIPTION
**Pull request by a631807682**
Close #4674

### CODE REVIEW

**Review by flycash — COMMENTED** [review]
I think this is not a good solution. We have `dbQueryLog`, and we will use it when `DEBUG` is true:
image

So as my understanding, when users use `DEBUG=true`, it should prints debug log.
And could you help to confirm that?

**Comment by a631807682** [comment]
https://github.com/beego/beego/blob/develop/client/orm/orm.go#L536
@flycash  Seems `DoTx` use new `TxDB` , so it lost query log when debug.

**Comment by flycash** [comment]
_txOrm := &txOrm{
		ormBase: ormBase{
			alias: o.alias,
			db:    newDbQueryLog(o.alias, &TxDB{tx:tx}),
		},
	}

**Comment by a631807682** [comment]
> _txOrm := &txOrm{
> ormBase: ormBase{
> alias: o.alias,
> db: newDbQueryLog(o.alias, &TxDB{tx:tx}),
> },
> }

we can't do this, `dbQuerier` print debug log although `Debug` flag is false, i create a test for it.

https://github.com/beego/beego/pull/4756/commits/9b14501c4336bd33fa6a4a023fed3d4624e653e9#diff-c3b3b1de3f657359cafc028e17ae972b7e2e1a5965fe23e02d89d2cac8e021c7R2916

**Comment by flycash** [comment]
nice, please resolve the conflicts and rebase your PR to one commit id

**Comment by flycash** [comment]
Please fix the golint issues(you can find them in `Files Changed`) and `DeepSource` issues (click `detail` and you can find it`.

Most of them were introduced by original developer, but I think you can help to fix them

**Comment by a631807682** [comment]
I will fix it later

**Review by flycash — APPROVED** [review]

**Comment by a631807682** [comment]
`getMiInd` is split into `getMi` and `getPtrMiInd` func by DeepSource issues, i'm not sure if it is the best way.

**Comment by flycash** [comment]
> `getMiInd` is split into `getMi` and `getPtrMiInd` func by DeepSource issues, i'm not sure if it is the best way. I will rebase all commit after review.

It looks good. Thank you very much.

**Pull request merged**
