### PR TITLE
Deprecated BeeMap and replace all usage with `sync.Map`

### PR DESCRIPTION
**Pull request by CarolineZhang666**

### CODE REVIEW

**Comment by jianzhiyao** [comment]
Why are  so many useless files committed?

**Comment by CarolineZhang666** [comment]
> Why are so many useless files committed?

sorry, I should add  (core/config/env/pkg  files ) to gitignore.

**Comment by jianzhiyao** [comment]
> > Why are so many useless files committed?
> 
> sorry, I should add (core/config/env/pkg files ) to gitignore.

Seems those files are still there.

**Comment by jianzhiyao** [comment]
close it for now, and follow it in https://github.com/beego/beego/pull/4616

**Pull request closed without merging**
