### PR TITLE
fix 4936: always transport request body

### LINKED ISSUE #4936: httplib的retry报错 http: ContentLength=252 with Body length 0
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
latest

2. What operating system and processor architecture are you using (`go env`)?
go1.15.2

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

func (b *BeegoHTTPRequest) sendRequest(client *http.Client) (resp *http.Response, err error) {
	// retries default value is 0, it will run once.
	// retries equal to -1, it will run forever until success
	// retries is setted, it will retries fixed times.
	// Sleeps for a 400ms between calls to reduce spam
	for i := 0; b.setting.Retries == -1 || i <= b.setting.Retries; i++ {
		resp, err = client.Do(b.req)
		if err == nil {
			return
		}
		time.Sleep(b.setting.RetryDelay)
	}
	return nil, berror.Wrap(err, SendRequestFailed, "sending request fail")
}

因为Do关闭了req.closeBody()，所以retry的时候  报错了

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

5. What did you see instead?

### PR DESCRIPTION
**Pull request by flycash**

### CODE REVIEW

**Comment by flycash** [comment]
@jptiancai, hi can you help to confirm this one? I will create a new release once you confirm it.

**Comment by jptiancai** [comment]
@flycash yes, this is  a global solution better than me.

**Comment by jptiancai** [comment]
@flycash pls add a new release tag, so this change can work!

**Comment by flycash** [comment]
OKK

**Pull request merged**
