### PR TITLE
Add Resp() method for response based on Accept header

### PR DESCRIPTION
**Pull request by maneeshbabu**
# Changes
- Closes https://github.com/beego/beego/issues/4492

### CODE REVIEW

**Review by flycash — APPROVED** [review]
Thank you!

**Comment by flycash** [comment]
Please fix golangci-lint issues and then I will merge this PR. You could find those issues on `Files Change` tab.

**Comment by maneeshbabu** [comment]
@flycash Sure, I will make those changes

**Comment by flycash** [comment]
Thank you !

**Pull request merged**
