### PR TITLE
feat: add write-delete cache mode

### PR DESCRIPTION
**Pull request by uzziahlin**
add write-delete cache mode under the client/cache

### CODE REVIEW

**Review by flycash — APPROVED** [review]
Thank you!

**Comment by flycash** [comment]
Please add this merge request into the .CHANGELOG file 😄

**Comment by uzziahlin** [comment]
> Please add this merge request into the .CHANGELOG file 😄

ok

**Comment by flycash** [comment]
just ignore the golangci-lint errors, it go some problems.

**Comment by uzziahlin** [comment]
> just ignore the golangci-lint errors, it go some problems.

ok

**Pull request merged**
