### PR TITLE
add template functions eq,lt to support uint and int compare.

### PR DESCRIPTION
**Pull request by jimashi**
add template functions eq,lt to support uint..uint64 and int..int64 compare.

### CODE REVIEW

**Comment by jianzhiyao** [comment]
### My test code:
We should not only provide the right example result but also provide some opposite examples
```
func Test_eq(t *testing.T) {
	tests := []struct {
		a      interface{}
		b      interface{}
		result bool
	}{
		{uint8(1), int(1), true},
		{uint8(3), int(1), false},
		{uint16(1), int(1), true},
		{uint16(3), int(1), false},
		{uint32(1), int(1), true},
		{uint32(3), int(1), false},
		{uint(1), int(1), true},
		{uint(3), int(1), false},
		{uint64(1), int(1), true},
		{uint64(3), int(1), false},


		{int8(-1), uint(1), false},
		{int16(-2), uint(1), false},
		{int32(-3), uint(1), false},
		{int64(-4), uint(1), false},
		{int8(1), uint(1), true},
		{int16(1), uint(1), true},
		{int32(1), uint(1), true},
		{int64(1), uint(1), true},

		{int8(-1), uint8(1), false},
		{int16(-2), uint8(1), false},
		{int32(-3), uint8(1), false},
		{int64(-4), uint8(1), false},
		{int8(1), uint8(1), true},
		{int16(1), uint8(1), true},
		{int32(1), uint8(1), true},
		{int64(1), uint8(1), true},

		{int8(-1), uint16(1), false},
		{int16(-2), uint16(1), false},
		{int32(-3), uint16(1), false},
		{int64(-4), uint16(1), false},
		{int8(1), uint16(1), true},
		{int16(1), uint16(1), true},
		{int32(1), uint16(1), true},
		{int64(1), uint16(1), true},

		{int8(-1), uint32(1), false},
		{int16(-2), uint32(1), false},
		{int32(-3), uint32(1), false},
		{int64(-4), uint32(1), false},
		{int8(1), uint32(1), true},
		{int16(1), uint32(1), true},
		{int32(1), uint32(1), true},
		{int64(1), uint32(1), true},

		{int8(-1), uint64(1), false},
		{int16(-2), uint64(1), false},
		{int32(-3), uint64(1), false},
		{int64(-4), uint64(1), false},
		{int8(1), uint64(1), true},
		{int16(1), uint64(1), true},
		{int32(1), uint64(1), true},
		{int64(1), uint64(1), true},
	}
	for _, test := range tests {
		if res, err := eq(test.a, test.b); err != nil {
			if res != test.result {
				t.Errorf("a:%v(%T) equals b:%v(%T) should be %v", test.a, test.a, test.b, test.b, test.result)
			}
		}
	}
}
```

**Comment by jimashi** [comment]
> ### My test code:
> We should not only provide the right example result but also provide some opposite examples
> 
> ```
> func Test_eq(t *testing.T) {
> 	tests := []struct {
> 		a      interface{}
> 		b      interface{}
> 		result bool
> 	}{
> 		{uint8(1), int(1), true},
> 		{uint8(3), int(1), false},
> 		{uint16(1), int(1), true},
> 		{uint16(3), int(1), false},
> 		{uint32(1), int(1), true},
> 		{uint32(3), int(1), false},
> 		{uint(1), int(1), true},
> 		{uint(3), int(1), false},
> 		{uint64(1), int(1), true},
> 		{uint64(3), int(1), false},
> 
> 
> 		{int8(-1), uint(1), false},
> 		{int16(-2), uint(1), false},
> 		{int32(-3), uint(1), false},
> 		{int64(-4), uint(1), false},
> 		{int8(1), uint(1), true},
> 		{int16(1), uint(1), true},
> 		{int32(1), uint(1), true},
> 		{int64(1), uint(1), true},
> 
> 		{int8(-1), uint8(1), false},
> 		{int16(-2), uint8(1), false},
> 		{int32(-3), uint8(1), false},
> 		{int64(-4), uint8(1), false},
> 		{int8(1), uint8(1), true},
> 		{int16(1), uint8(1), true},
> 		{int32(1), uint8(1), true},
> 		{int64(1), uint8(1), true},
> 
> 		{int8(-1), uint16(1), false},
> 		{int16(-2), uint16(1), false},
> 		{int32(-3), uint16(1), false},
> 		{int64(-4), uint16(1), false},
> 		{int8(1), uint16(1), true},
> 		{int16(1), uint16(1), true},
> 		{int32(1), uint16(1), true},
> 		{int64(1), uint16(1), true},
> 
> 		{int8(-1), uint32(1), false},
> 		{int16(-2), uint32(1), false},
> 		{int32(-3), uint32(1), false},
> 		{int64(-4), uint32(1), false},
> 		{int8(1), uint32(1), true},
> 		{int16(1), uint32(1), true},
> 		{int32(1), uint32(1), true},
> 		{int64(1), uint32(1), true},
> 
> 		{int8(-1), uint64(1), false},
> 		{int16(-2), uint64(1), false},
> 		{int32(-3), uint64(1), false},
> 		{int64(-4), uint64(1), false},
> 		{int8(1), uint64(1), true},
> 		{int16(1), uint64(1), true},
> 		{int32(1), uint64(1), true},
> 		{int64(1), uint64(1), true},
> 	}
> 	for _, test := range tests {
> 		if res, err := eq(test.a, test.b); err != nil {
> 			if res != test.result {
> 				t.Errorf("a:%v(%T) equals b:%v(%T) should be %v", test.a, test.a, test.b, test.b, test.result)
> 			}
> 		}
> 	}
> }
> ```

Thanks!

**Comment by flycash** [comment]
Please add change log into CHANGELOG.md, so that we could pass all validation.

**Comment by jianzhiyao** [comment]
please complete test cases, so we can merge your pr.

**Comment by jimashi** [comment]
> please complete test cases, so we can merge your pr.

Hello,is unit test?

**Comment by jianzhiyao** [comment]
> > please complete test cases, so we can merge your pr.
> 
> Hello,is unit test?

yes, like what i provided you.

**Comment by jimashi** [comment]
> > > please complete test cases, so we can merge your pr.
> > 
> > 
> > Hello,is unit test?
> 
> yes, like what i provided you.

Ok,thanks!

**Comment by flycash** [comment]
golint and CI failed

**Comment by jimashi** [comment]
> golint and CI failed

Please help me,how to finish it.

**Comment by flycash** [comment]
Sorry for late reply since I forget to reply :(. For CI, you just check why tests failed, and if you ensure that your change doesn't cause the failure, you can ignore it and let me retry test. For go-lint, you check "change files" tab and you can find the comments.

**Comment by jimashi** [comment]
> Sorry for late reply since I forget to reply :(. For CI, you just check why tests failed, and if you ensure that your change doesn't cause the failure, you can ignore it and let me retry test. For go-lint, you check "change files" tab and you can find the comments.

Thank you!

**Comment by flycash** [comment]
tests still failed. please fix it

**Comment by jimashi** [comment]
> tests still failed. please fix it

ok,fix it again.

**Comment by jimashi** [comment]
> tests still failed. please fix it

hello,test 1.14 failed,is my code error?

**Comment by flycash** [comment]
thank you very much!!

**Comment by jimashi** [comment]
Not at all.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "beego/beego"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月26日(星期六) 凌晨0:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [beego/beego] add template functions eq,lt to support uint and int compare. (#4607)





 
thank you very much!!

**Pull request merged**
