### PR TITLE
Test on Go v1.15.x & v1.16.x

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Comment by flycash** [comment]
it failed on go1.16, you need to run `go mod tidy`

**Comment by Loyalsoldier** [comment]
I find out that if change `go 1.14` in `go.mod` to `go 1.16`, then run `go mod tidy`, `go.sum` is a bit different. But this is NOT the case that led to failure to tests in Travis Go v1.16.x.

**Comment by flycash** [comment]
How about run `go mod tidy` in our CI? It means that we force the Travis run `go mod tidy` before it run other validation.
I am not sure if it's a good idea.

**Comment by Loyalsoldier** [comment]
I would like to migrate the CI to GitHub Actions.

**Comment by Loyalsoldier** [comment]
Done.

**Comment by flycash** [comment]
> I would like to migrate the CI to GitHub Actions if needed.

You could do that. I plan to migrate it but it's not easy for me. Thank you!

**Comment by Loyalsoldier** [comment]
> > I would like to migrate the CI to GitHub Actions if needed.
> 
> You could do that. I plan to migrate it but it's not easy for me. Thank you!

You can merge this first. I'm afraid the migration will not happen shortly.

**Pull request merged**
