### PR TITLE
Add more information into debugLogQueies logMap

### PR DESCRIPTION
**Pull request by LumenShip**
Refactor debugLogQueries function in orm_log.go

The debugLogQueries function in orm_log.go was modified to fix typos, streamline the formatting of log entries, and include additional data. Key changes include the addition of new entries to logMap, including "alias_name", "operation", "query", "cons", and "err". DebugLog also replaces logs.DebugLog to output the log entry.

### CODE REVIEW

**Comment by LumenShip** [comment]
issue #5668

**Comment by LumenShip** [comment]
Test Code:
image

+ Before:
  
  - success:
   
image

  - fail:
  
image

+ After:
  
  - success:
  
image

  - fail:

image

**Comment by flycash** [comment]
good, I think you can raise a merge request to master branch, to that I can release this tidy change as soon as possible.

**Comment by LumenShip** [comment]
Thank you, pull request has been sent.

**Comment by flycash** [comment]
I will merge master branch to develop. so I close this.

**Pull request closed without merging**
