### PR TITLE
Integration: DeepSource

### PR DESCRIPTION
**Pull request by withshubh**
PR #4513 fixed some of the issues using DeepSource. Have a look at the issues caught by DeepSource [here](https://deepsource.io/gh/withshubh/beego/issues/?category=recommended). You can also fix most of the issues using DeepSource auto-fix feature.

Integrating DeepSource to continuously analyze your repository for code quality issues:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Create a `.deepsource.toml` configuration specific to this repo or simply merge this PR which includes the configuration which I used to run analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/beego/beego/)

### CODE REVIEW

**Review by flycash — APPROVED** [review]
Let's try this

**Comment by withshubh** [comment]
Thank @flycash :sparkling_heart: 

Do let me know your feedback once you've activated the analysis :)

**Comment by flycash** [comment]
Thank you, and hope you could do more contributions to Beego

**Comment by withshubh** [comment]
Hey @flycash Did you try DeepSource?

Would love to hear your feedback :)

**Pull request merged**
