### PR TITLE
Add:Get response with media type

### PR DESCRIPTION
**Pull request by Feizekai**
In my work, there is a business situation: the client needs content-type in the server's return to be in other formats by setting the content-type of the request header to the json format. So I want to add a http request method that allows the client to specify the content-type of the return body while sending the request.

### CODE REVIEW

**Comment by Feizekai** [comment]
The fault from DeepSource Analysis is native

**Comment by flycash** [comment]
I don't get your point, you can specify the media type when you construct the http request

**Comment by Feizekai** [comment]
> I don't get your point, you can specify the media type when you construct the http request

But sometimes we need to define the media tpye as json in request and get a response with zip

> I don't get your point, you can specify the media type when you construct the http request


But sometimes we need to define the media tpye as json in request and get a response with zip

**Comment by flycash** [comment]
I mean, it looks like you can use filter directory? no need to have a new
structure ?

**Pull request closed without merging**
