### PR TITLE
Chore: update dependencies

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Review by flycash — COMMENTED** [review]
Do you run `go mod tidy` command?

**Comment by flycash** [comment]
> Do you run `go mod tidy` command?

There is a big change that from 1.16, golang requires we ran `go mod tidy` to add all dependencies into `go.sum`, so you'd better run it before committing changes.

**Comment by Loyalsoldier** [comment]
Yeah, I ran `go mod tidy` to generate `go.sum`.

**Comment by flycash** [comment]
Could you add the PR to `CHANGELOG.md` ?

**Comment by Loyalsoldier** [comment]
Done.

**Pull request merged**
