### PR TITLE
[WIP]Feature easy cron

### PR DESCRIPTION
**Pull request by changsongl**
This is for issue #4429. I finish all APIS for easy crontab. Do you have any suggestion for this implementation? It might be some error in the code, and I will fix it during writing unit tests. @flycash @jianzhiyao

### CODE REVIEW

**Review by flycash — COMMENTED** [review]
nextFunc and EasyTaskFunc is similar.
One option is that use nextFunc, and remove EasyTaskFunc, and then calculate the time in *StartAt methods;
Another option is no need to introduce these two abstactions. Methods `Repeat` and `*StartAt`
return cron expression;

**Comment by changsongl** [comment]
> nextFunc and EasyTaskFunc is similar.
> One option is that use nextFunc, and remove EasyTaskFunc, and then calculate the time in *StartAt methods;
> Another option is no need to introduce these two abstactions. Methods `Repeat` and `*StartAt`
> return cron expression;

I think I will go with plan 1. I don't think we can transfer repeat method to cron expression. 

For example, if I want to repeat a job for every 11 minutes, the expression could be * */11 * * * *. The fact it will cause a false running time (4:00:00).
````shell
2021-02-28 03:44:00
2021-02-28 03:55:00
2021-02-28 04:00:00
````

**Comment by changsongl** [comment]
I have made the change for the review, let me know if you have more suggestions.

**Review by flycash — COMMENTED** [review]
Nice job, and please add more unit tests.

**Comment by flycash** [comment]
You could ignore the Sonar problems because I think it's hard to refactor the code to reduce the duplication.

**Pull request closed without merging**
