### PR TITLE
Chore: format code

### PR DESCRIPTION
**Pull request by Loyalsoldier**
- Run `go fmt ./...` to format code
- Use https://github.com/daixiang0/gci to format import

### CODE REVIEW

**Review by jianzhiyao — APPROVED** [review]
LGTM

**Comment by flycash** [comment]
Please fix CHANGELOG. And you don't need to resolve deepsource issues.

**Comment by Loyalsoldier** [comment]
> Please fix CHANGELOG. And you don't need to resolve deepsource issues.

Wait for 5 minutes.

**Comment by Loyalsoldier** [comment]
Done.

**Pull request merged**
