### PR TITLE
improve code quality

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes

- Fix unnecessary allocations due to `Index` calls
- Fix inefficient string comparison
- Remove unnecessary wrapping of function call
- Remove unnecessary use of slice
- Replace `time.Now().Sub` with `time.Since`

### CODE REVIEW

**Review by flycash — APPROVED** [review]

**Comment by flycash** [comment]
Thank you!

**Comment by withshubh** [comment]
@flycash 

I would like to share that I ran [DeepSource](https://deepsource.io/) analyzer on my fork of this repository to detect these issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/beego/issues/?category=recommended).

DeepSource is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

Can I submit an issue as a feature request for DeepSource integration or PR(consisting of a configuration file only)?
You can merge the configuration file to activate the analysis to continuously analyze the repo and fix code quality issues.

**Comment by flycash** [comment]
Thank you!
But could you share more details about the DeepSource and I want to know the difference between Sonar and DeepSource。

**Comment by withshubh** [comment]
@flycash 
> But could you share more details about the DeepSource 

DeepSource is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

It is a service that runs in parallel to CI. In most (almost all) cases: DeepSource checks are gonna finish before the CI checks.

After integrating DeepSource, you can go ahead and remove the linting checks from your CI as DeepSource internally takes care of that. This will make your CI pipeline simpler (and faster).

>and I want to know the difference between Sonar and DeepSource。

- DeepSource analyzers detects in-depth issues than just surface-level issues. For instance, DeepSource Go analyzer detects over [214 issues](https://deepsource.io/directory/analyzer/go/) as of today. SonarQube detects [around 38](https://rules.sonarsource.com/go).
- Ability to autofix issues and auto format code.
- DeepSource guarantees less than 5% false positives.
- Much better integration and developer experience.

**Comment by withshubh** [comment]
Hey @flycash Shall I submit a new PR with config file for DeepSource?

**Comment by flycash** [comment]
> Hey @flycash Shall I submit a new PR with config file for DeepSource?

Yes, you could try that.

**Comment by withshubh** [comment]
@flycash I have submitted the PR :sparkling_heart:

**Pull request merged**
